# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bharrington"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "bharrington"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group minor and patch updates together
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      testing:
        patterns:
          - "*junit*"
          - "*mockito*"
          - "*robolectric*"
          - "*espresso*"
          - "*truth*"
    # Ignore specific updates if needed
    ignore:
      # Example: ignore major version bumps for specific packages
      # - dependency-name: "androidx.core:core-ktx"
      #   update-types: ["version-update:semver-major"]
